### ISSUE TITLE
Crash during conversion after download

### ISSUE THREAD

**Issue by adrien-berchet** [brainglobe/morphapi#12]
Hi

In some cases `morphapi` crashes when it tries to convert the morphology after downloading it into a `morphapi.morphology.morphology.Neuron` object. For example, http://neuromorpho.org/dableFiles/pinto/CNG%20version/TREATED2.CNG.swc has no point in soma so `morphapi` crashes when it tries to get the position of the soma: `soma_pos = nrn.soma.points[0, :3]`.
In my case, I only need the files but not the `morphapi` objects, so it is a bit frustrating that it fails because of something I don't need.
I think about 2 solutions to fix this behavior:

1. add an option to the `download_neurons` method to only download the files but do not convert them, so the method would just return `None`.
2. add a try/except statement to set `self.points` to `None` if an exception is raised during the conversion.

I can make a PR for that but I need to know which solution you prefer (of course it can be another solution I didn't think about).

**Comment by FedeClaudi** [comment]
Hi Adrien, 

Morphapi is not actively under development currently so thanks for working on it and sending these PRs. If you want to get more directly involved in morphapi's development we can get you in the github org and on slack for more informal chats about. 

I think the best option should be best, leaving it as true by default. But perhaps we can also have a `try/catch` that explains what caused the error and how the user can use `download_neuron`'s argument to avoid it, what do you think?

**Comment by adrien-berchet** [comment]
I surely can take part of the development of morphapi, we want to use it so that's definitely part of my job. Thanks for proposing :)

Indeed if we add a new option we would keep the current behavior as default. We could even have 3 values for this parameter:
1. current behavior: we want to load all downloaded neurons.
2. we try to load all downloaded neurons but fail silently (so the file is downloaded but the `self.points` attribute is set to `None`.
3. we just download the files but don't load them.

I don't know if 2. could make sense for a user?
I am going to work on a new PR today with at least 1. and 3. .

**Comment by adrien-berchet** [comment]
I agree for silent failing, let's only keep the solutions 1. and 3. then.

I think I found your email from your github.io page, I am going to try that.

For now I only use morphapi, not brainrender.
