### ISSUE TITLE
Cannot fetch neurons with Mouselight API

### ISSUE THREAD

**Issue by Antorithms** [brainglobe/morphapi#23]
I am unable to download neurons using the MouseLightAPI (version 0.1.7 of morphapi) , for all neurons I try to download, I receive the follwing error: 

> Could not fetch the neuron AA1544 for the following reason: URL request failed: Not Found ; url: http://neuromorpho.org/api/neuron/name/AA1544

Going to the URL also suggests that the link is incorrect (

> {"status":404,"error":"Not Found","message":"Requested neuron not found","path":"/api/neuron/name/AA1544"}

).
**To Reproduce**
I tried to run the following code, but no matter which neuron metadata subset from the Mouselight database I provide, it does not work. 

```
from morphapi.api.mouselight import MouseLightAPI
mlapi = MouseLightAPI()


neurons_metadata = mlapi.fetch_neurons_metadata(
    filterby="soma", filter_regions=["SSs"]
)


neurons = mlapi.download_neurons(neurons_metadata[0])

```

I expect to be able to download the swc files for the neurons to process them.

**Computer used (please complete the following information):**

- OS: Windows 10.
- Hardware specs 128 GB RAM, Intel I9 CPU].

**Comment by adrien-berchet** [comment]
Hi @Antorithms 
Thanks for your report, as far as I can see this is just because HTTP is no more supported and we have to switch to HTTPS. #24 should fix this.

**Comment by adrien-berchet** [comment]
The new `0.1.8` release should fix this issue.
