### ISSUE TITLE
Change default branch to `main`. 

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/morphapi#26]
@FedeClaudi are you happy for me to change the default branch to `main` for consistency with the other BG tools (and GitHub default)?

**Comment by alessandrofelder** [comment]
I've taken the liberty of addressing this via the Github settings.

GitHub's instructions to update local clones are below:
```bash
git branch -m master mainmaster
git fetch origin
git branch -u origin/mainmaster mainmaster
git remote set-head origin -a
```
