### ISSUE TITLE
Fix root cause of warnings in tests

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/morphapi#31]
Currently, we ignore some warnings in our tests via `pytest.ini` settings:
```
filterwarnings =
    ignore:distutils Version classes are deprecated:DeprecationWarning
    ignore:The hookimpl CovPlugin.pytest_.* uses old-style configuration options:pytest.PytestDeprecationWarning
```
Instead of ignoring some warnings with a pytest filter, we should avoid them happening in the first place.

**Comment by alessandrofelder** [comment]
Related to #30 .

**Comment by adamltyson** [comment]
Closing, as we no longer filter any warnings.
