### ISSUE TITLE
Change the base url for fetching from neuromorpho

### ISSUE THREAD

**Issue by IgorTatarnikov** [brainglobe/morphapi#71]
Based on the [API docs](https://neuromorpho.org/apiReference.html#introduction) we should use http://cng.gmu.edu:8080/api as the URL. This might fix some of the uptime issues we've faced in the past. Perhaps http://cng.gmu.edu:8080/api is still up when https://neuromorpho.org/api is down?

**Comment by adamltyson** [comment]
Sounds like a good idea to me, especially because currently http://cng.gmu.edu:8080/api is up and https://neuromorpho.org/api is down
