### ISSUE TITLE
Criteria are not filtered in neuromorpho query

### ISSUE THREAD

**Issue by lidakanari** [brainglobe/morphapi#9]
Hello, 

I have tried the query criteria for neuromorpho download and I found an error with the current implementation. In line:
https://github.com/brainglobe/morphapi/blob/3bb07bc80260b9a93cd98f5d073f7900065091b3/morphapi/api/neuromorphorg.py#L83

it should be instead 
`                url += "&fq="`
according to the NeuroMorpho filtering query:
http://neuromorpho.org/apiReference.html#neuron-filter-query

I think this should fix the problem. 

Best,
Lida

**Comment by FedeClaudi** [comment]
Thanks!
Would you like to send a pull request with the fix?

**Comment by lidakanari** [comment]
Sure, I can send a PR.

**Comment by FedeClaudi** [comment]
fixed by https://github.com/brainglobe/morphapi/pull/10
